export const LOGIN_STATUS_CHANGED = "LOGIN STATUS CHANGED";

export const FACEBOOK_LOGIN = "LOG IN TO FACEBOOK";
export const FACEBOOK_LOGGEDIN = "LOGGED IN TO FACEBOOK";

export const FACEBOOK_LOGOUT = "LOGOUT FROM FACEBOOK";
export const FACEBOOK_LOGGEDOUT = "LOGGED OUT FROM FACEBOOK";


export const GET_USER_DATA = "GET USER DATA";
export const USER_DATA_RECEIVED = "USER DATA RECEIVED";

export const GET_USER_FRIENDS = "GET USER FRIENDS";
export const USER_FRIENDS_RECEIVED = "USER FRIENDS RECEIVED";


export const GET_USER_INBOX = "GET USER INBOX";
export const USER_INBOX_RECEIVED = "USER INBOX RECEIVED";